version: "3.9"

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build: ./backend
    ports:
      - "5050:5050"  # Use 5050 to avoid conflict with macOS
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/formdb
      - PORT=5050

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
